server:
  port: 9999
  servlet:
    context-path: /example-application
spring:
  datasource:
    #   driver-class-name:
    url: jdbc:postgresql://localhost:5555/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
